# Generated by Django 4.0 on 2021-12-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='Error URL')),
                ('criticality', models.CharField(choices=[('LIGHT', 'LIGHT'), ('MODERATE', 'MODERATE'), ('URGENT', 'URGENT'), ('CRITICAL', 'CRITICAL')], max_length=100)),
                ('tools', models.CharField(choices=[('MIDELIVERY', 'MIDELIVERY'), ('MISHOWROOM', 'MISHOWROOM'), ('HUB', 'HUB')], max_length=100)),
                ('country', models.CharField(choices=[('US', 'US'), ('CANADA', 'CANADA'), ('PR', 'PR')], max_length=100)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('complaint_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='core.appuser')),
                ('currently_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.ticket')),
            ],
        ),
    ]
