# Generated by Django 4.0 on 2021-12-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ticket', '0002_alter_ticketfiles_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.appuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_comments', to='ticket.ticket')),
            ],
        ),
    ]
