# Generated by Django 4.0 on 2021-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
