# Generated by Django 4.0 on 2021-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_is_archived_alter_ticket_criticality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
