# Generated by Django 4.0 on 2021-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlogs',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT ACKNOLEDGE', 'Not Acknoledge'), ('ACKNOLEDGE', 'Acknoledge'), ('IN DEVELOPMENT', 'In Development'), ('TESTING', 'Testing'), ('DEPLOYED', 'Deployed'), ('CLOSED', 'Closed')], max_length=100, null=True),
        ),
    ]
